# Used to populate the navigation.
# The top nav only uses the top level of nav items.
# The bottom nav also uses the secondary_nav items.
#
kramdown:
  auto_ids: true 
# Current assumptions:
# Top level nav items are all internal links at the top level.
# Secondary nav items assume they are nested under the folder specified by their
# parent nav item.
# Secondary nav items can be external links. You must set the "external: true"
# value on them.
nav_items:
  - url: 'about'
    label: 'About'
  - url: 'upcoming_events'
    label: 'Events'
    secondary_nav:
    - url: 'upcoming_events#online-office-hours'
      label: 'Office Hours'
    - url: 'upcoming_events#in-person-training'
      label: 'In Person'
  - url: 'training'
    label: 'Training Program'
    secondary_nav:
    - url: 'training/code_of_conduct#workshops'
      label: 'Workshops'
    - url: 'training/code_of_conduct#training-materials'
      label: 'Materials'
  - url: 'resources'
    label: 'Resources'
    secondary_nav:
      - url: 'resources/code_of_conduct'
        label: 'Code of Conduct'
      - url: 'resources/reporting'
        label: 'Reporting Guidelines'
      - url: 'resources/index'
        label: 'Resource Guide'
  - url: 'get_involved'
    label: 'Get Involved'
