# Used to populate the navigation.
# The top nav only uses the top level of nav items.
# The bottom nav also uses the secondary_nav items.
#
collections:
  resources:
    output: true
nav_items:
  - url: '/about'
    label: 'About'
  - url: '/upcoming_events.html'
    label: 'Events'
    secondary_nav:
    - url: '/upcoming_events.html#online-office-hours'
      label: 'Office Hours'
    - url: '/upcoming_events.html#in-person-training'
      label: 'In Person'
  - url: '/training'
    label: 'Training Program'
    secondary_nav:
    - url: '/training/code_of_conduct/index.html#workshops'
      label: 'Workshops'
    - url: 'training/code_of_conduct/index.html#training-materials'
      label: 'Materials'
  - url: '/resources'
    label: 'Resources'
    secondary_nav:
      - url: '/resources/code_of_conduct.html'
        label: 'Codes of Conduct'
      - url: '/resources/reporting.html'
        label: 'Reporting Guidelines'
      - url: '/resources/incident_response.html'
        label: 'Incident Response Plans'
      - url: '/resources/accountability.html'
        label: 'Community Accountability'
  - url: '/get_involved'
    label: 'Get Involved'
